version: 1

run:
  timeout: 5m
  build-tags:
    - integration
    - no_glfw

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - gosec
    - revive
  disable:
    - errcheck
    - gosimple
    - unused

linters-settings:
  gofmt:
    simplify: true
  staticcheck:
    checks: ["all", "-SA1019"]
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - whyNoLint
  gosec:
    excludes:
      - G204
      - G304

issues:
  exclude-rules:
    - path: "_windows\\.go$"
      linters:
        - gosec
        - gocritic
    
    - path: "_other\\.go$"
      linters:
        - gosec
        - gocritic
    
    - path: "_test\\.go$"
      linters:
        - gosec
        - gocritic
    
    - path: "pkg/spdreader"
      linters:
        - gosec
    
    - path: "pkg/gui/(storage_info|spd_reader|admin_check|single_instance)"
      linters:
        - gosec
        - gocritic