name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Bump version
        id: bump
        run: |
          chmod +x scripts/bump-version.sh
          ./scripts/bump-version.sh ${{ github.event.inputs.bump_type }}
          
          # Get the new version
          NEW_VERSION=$(cat VERSION)
          echo "new_version=v${NEW_VERSION}" >> $GITHUB_OUTPUT
          
      - name: Push changes
        run: |
          git push origin main
          git push origin ${{ steps.bump.outputs.new_version }}
          
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.new_version }}
          release_name: Release ${{ steps.bump.outputs.new_version }}
          draft: false
          prerelease: false
          body: |
            ## Changes in this release
            
            <!-- Add release notes here -->
            
            ### Full Changelog
            https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ steps.bump.outputs.new_version }}